name: Ansible Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible and ansible-lint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible ansible-lint

      - name: Create custom .ansible-lint.yml
        run: |
          echo "anchors: enable" > .ansible-lint.yml
          echo "braces: enable" >> .ansible-lint.yml
          echo "brackets: enable" >> .ansible-lint.yml
          echo "colons: enable" >> .ansible-lint.yml
          echo "commas: enable" >> .ansible-lint.yml
          echo "comments:" >> .ansible-lint.yml
          echo "  level: warning" >> .ansible-lint.yml
          echo "comments-indentation:" >> .ansible-lint.yml
          echo "  level: warning" >> .ansible-lint.yml
          echo "document-end: disable" >> .ansible-lint.yml
          echo "document-start:" >> .ansible-lint.yml
          echo "  level: warning" >> .ansible-lint.yml
          echo "empty-lines: enable" >> .ansible-lint.yml
          echo "empty-values: disable" >> .ansible-lint.yml
          echo "float-values: disable" >> .ansible-lint.yml
          echo "hyphens: enable" >> .ansible-lint.yml
          echo "indentation: enable" >> .ansible-lint.yml
          echo "key-duplicates: enable" >> .ansible-lint.yml
          echo "key-ordering: disable" >> .ansible-lint.yml
          echo "line-length: enable" >> .ansible-lint.yml
          echo "new-line-at-end-of-file: enable" >> .ansible-lint.yml
          echo "new-lines: enable" >> .ansible-lint.yml
          echo "octal-values: disable" >> .ansible-lint.yml
          echo "quoted-strings: disable" >> .ansible-lint.yml
          echo "trailing-spaces: enable" >> .ansible-lint.yml
          echo "truthy:" >> .ansible-lint.yml
          echo "  level: warning" >> .ansible-lint.yml

      - name: Run ansible-lint
        run: |
          # Find all .yml or .yaml files and run ansible-lint on each
          ansible_files=$(find . -name '*.yml' -o -name '*.yaml')
          if [ -z "$ansible_files" ]; then
            echo "No Ansible files found to lint."
          else
            for file in $ansible_files; do
              echo "Linting $file"
              ansible-lint "$file" -c .ansible-lint.yml || true # Continue even if linting fails
            done
          fi