name: Ansible Linting

skip_list:
  - "1010"  # Rule ID for "No new line at end of file"
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible_files=$(find . -name '*.yml' -o -name '*.yaml')
          if [ -z "$ansible_files" ]; then
            echo "No Ansible files found to lint."
          else
            for file in $ansible_files; do
              echo "Linting $file"
              ansible-lint "$file"
            done
          fi