name: Ansible Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible and ansible-lint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible ansible-lint

      - name: Create custom .ansible-lint.yml
        run: |
          # Create a valid .ansible-lint.yml configuration file
          echo "skip_list:" > .ansible-lint.yml
          echo "  - 'ANSIBLE0006'" >> .ansible-lint.yml
          echo "  - 'ANSIBLE0012'" >> .ansible-lint.yml  # Example of skipping another rule
          echo "  - 'ANSIBLE0020'" >> .ansible-lint.yml  # You can add more rules as needed

      - name: Run ansible-lint
        run: |
          # Find all .yml or .yaml files and run ansible-lint on each
          ansible_files=$(find . -name '*.yml' -o -name '*.yaml')
          if [ -z "$ansible_files" ]; then
            echo "No Ansible files found to lint."
          else
            for file in $ansible_files; do
              echo "Linting $file"
              ansible-lint "$file" -c .ansible-lint.yml || true # Continue even if linting fails
            done
          fi