name: YAML Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      # Create .yamllint.yml file to configure the linter
      - name: Create .yamllint.yml to Skip Rules
        run: |
          echo "extends: default" > .yamllint.yml
          echo "ignore: []" >> .yamllint.yml  # Add any specific files or paths to ignore
          echo "rules:" >> .yamllint.yml
          echo "  line-length:" >> .yamllint.yml  # Example of rule configuration
          echo "    max: 120" >> .yamllint.yml  # Example to set max line length to 120

      # Run yamllint to lint all .yml and .yaml files
      - name: Run yamllint
        run: |
          yaml_files=$(find . -name '*.yml' -o -name '*.yaml')
          if [ -z "$yaml_files" ]; then
            echo "No YAML files found to lint."
          else
            for file in $yaml_files; do
              echo "Linting $file"
              yamllint "$file"
            done