name: Bash Linting

on:
  pull_request:
    paths:
      - '**/*.sh'
  push:
    branches:
      - main
    paths:
      - '**/*.sh'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ShellCheck
        uses: ludeeus/action-shellcheck@v1

      - name: Run ShellCheck
        run: |
          # Find all .sh files and check them with ShellCheck
          find . -name '*.sh' -print0 | xargs -0 shellcheck