name: Bash Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          # Find all .sh files and run ShellCheck only if files are found
          if find . -name '*.sh' | grep -q .; then
            find . -name '*.sh' -print0 | xargs -0 shellcheck
          else
            echo "No .sh files found to lint."
          fi