name: Bash Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ShellCheck
        uses: ludeeus/action-shellcheck@v1

      - name: Run ShellCheck
        run: |
          # Find all .sh files and check them with ShellCheck
          find . -name '*.sh' -print0 | xargs -0 shellcheck