name: Bash Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          # Find all .sh files and run ShellCheck on each
          sh_files=$(find . -name '*.sh')
          if [ -z "$sh_files" ]; then
            echo "No .sh files found to lint."
          else
            for file in $sh_files; do
              echo "Linting $file"
              shellcheck "$file" || true ##remove the ||true once all scripts have been reviewed and errors corrected
            done
          fi